mb1m = 'data/mb1m/'
myket = 'data/myket/'

coo_record = 'coo_record.npz'
train_coo_record = 'train_coo_record.npz'
val_coo_record = 'val_coo_record.npz'
test_coo_record = 'test_coo_record.npz'
train_skew_coo_record = 'train_skew_coo_record.npz'
timestamps = 'timestamps.npy'
popularity = 'popularity.npy'
blend_popularity = 'popularity_blend.npy'
train_coo_adj_graph = 'train_coo_adj_graph.npz'
train_skew_coo_adj_graph = 'train_skew_coo_adj_graph.npz'
train_blend_coo_adj_graph = 'train_blend_coo_adj_graph.npz'
